chat/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name="chat"

urlpatterns=[
    path('chat/',views.index,name='index'),
    path('chat/<int:id>/',views.get_messages,name='messages'),
]

user_profile/urls.py
from django.urls import path, include
from django.contrib import auth
from django.contrib.auth.views import LoginView
from . import views

urlpatterns=[
    path('register/',views.register,name="register"),
    path('login/',views.Login.as_view(), name='login'),
    path('logout/',views.logout_view, name='logout'),
    path('orders/<path>',views.download,name='download'),
    path('orders/',views.orders,name='orders'),
    path('order/',views.order, name='create_order'),
    path('order/<int:id>/',views.revoke_order,name="order"),
]

web_studio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('',include('homepage.urls')),
    path('',include('user_profile.urls')),
    path('',include('chat.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('jet/',include('jet.urls','jet')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.STATIC_ROOT)

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.utils import timezone
from datetime import timedelta
from django.urls import reverse
from django.core.validators import ValidationError
from manager.models import Manager

class Order(models.Model):
    STATUS_CHOICES=(
        ('processing','Processing'),
        ('deviation','Deviation'),
        ('development','Development'),
        ('done','Done')
    )
    id_order=models.AutoField(primary_key=True)
    user=models.ForeignKey(User,related_name='orders',on_delete=models.PROTECT)
    status=models.CharField(max_length=11, choices=STATUS_CHOICES,default='processing')
    description=models.TextField()
    deadline=models.DateTimeField()
    price=models.IntegerField(null=True,blank=True,validators=[MinValueValidator(1),])
    paid=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    manager=models.ForeignKey(Manager,related_name='manager_orders',on_delete=models.PROTECT,null=True)
    file=models.FileField(null=True,blank=True)

    def __str__(self):
        return  self.created.strftime('%H:%M:%S %d.%m.%Y ')+self.user.email
    class Meta:
        db_table='orders'
        ordering=('-created',)
        verbose_name='Order'
        verbose_name_plural='Orders'

    def get_absolute_url(self):
        return reverse('order',args=[
            self.pk,
        ])

user_profile/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Order
from django.utils import timezone
from .validators import validate_deadline
from django.contrib.auth.forms import AuthenticationForm
from django.core.validators import ValidationError

class UserRegistrationForm(forms.ModelForm):
    username=forms.CharField(label='Username',widget=forms.TextInput(attrs={'placeholder': 'Username'})) 
    first_name=forms.CharField(label='First name',widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    last_name=forms.CharField(label='Last name',widget=forms.TextInput(attrs={'placeholder': 'Last name'}))
    email=forms.EmailField(label='Email',widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2=forms.CharField(label='Reapeat password',widget=forms.PasswordInput(attrs={'placeholder': 'Reapeat password'}))

    class Meta:
        model=User
        fields=('username','email','first_name','last_name',)

    def clean_password2(self):
        cd=self.cleaned_data
        if cd['password']!=cd['password2']:
            raise forms.ValidationError('Password don\'t match.')
        return cd['password2']

class OrderCreationForm(forms.ModelForm):
    deadline=forms.DateTimeField(
    label='Deadline',
    widget=forms.DateTimeInput(),
    validators=(validate_deadline,),initial=timezone.now())

    def validate_deadline(value):
        if value!=timezone.now():
            return ValidationError("The date cannot be in the past!")
    class Meta:
        model=Order
        fields=('description',)


class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))

user_profile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import UserRegistrationForm, OrderCreationForm
from .models import Order
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CustomAuthForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import HttpResponse, Http404
import os
from django.conf import settings
from chat.models import Chat
from django.contrib.auth.models import User

user_login_required=user_passes_test(lambda user: user.is_staff==False and user.is_superuser==False, login_url='/login')

def non_staff_user_required(view_func):
    decorated_view_func=login_required(user_login_required(view_func))
    return decorated_view_func


def register(request):
    if request.method=='POST':
        user_form=UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user=user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            admins = User.objects.filter(is_superuser=True) # select all admins
            for admin in admins:
                chat = Chat()  #create chat
                chat.save()
                chat.users.add(new_user,admin)  #add user and admin
            if new_user is not None:
                if new_user.is_active:
                    login(request, new_user)
                    return redirect('orders')
                else:
                    return redirect('register')
    else:
        user_form=UserRegistrationForm()
    return render(request,'registration/register.html',{'form':user_form})

@non_staff_user_required
def logout_view(request):
    logout(request)
    return redirect('/')

@non_staff_user_required
def orders(request):
    if request.method=='POST':
        pass    
    else:
        orders_list=Order.objects.filter(user_id=request.user.id)
        paginator=Paginator(orders_list,2)
        page=request.GET.get('page')
        try:
            orders=paginator.page(page)
        except PageNotAnInteger:
            orders=paginator.page(1)
        except EmptyPage:
            orders=paginator.page(paginator.num_pages)
    return render(request,'user_profile/orders.html',{'orders':orders})

@non_staff_user_required
def order(request):
    if request.method=='POST':
       order_form=OrderCreationForm(request.POST)
       if order_form.is_valid():
           new_order=order_form.save(commit=False)
           new_order.user=request.user
           new_order.deadline=order_form.cleaned_data['deadline']
           new_order.save()
           return redirect('orders')
    else:
        order_form=OrderCreationForm()
    return render(request,'user_profile/order.html',{'form':order_form})

@non_staff_user_required
def revoke_order(request,id):
    order=get_object_or_404(Order,pk=id)
    if request.method=="POST":
        order.status='deviation'
        order.save()
        return redirect('orders')
    else:
        return render(request,'user_profile/detail.html',{'order':order})

class Login(LoginView):
    authentication_form=CustomAuthForm
    template_name='registration/login.html'

@non_staff_user_required
def download(request,path):
    if request.method=='POST':
        file_path=os.path.join(settings.BASE_DIR,'media/'+path)
        if os.path.exists(file_path):
            with open(file_path,'rb') as fh:
                response=HttpResponse(fh.read())
                response['Content-Disposition'] = 'attachment; filename='+os.path.basename(file_path)
                return response
    raise Http404

templates/user_profile/detail.html
{% extends 'index.html' %}

{% load static %}

{% block title %}Order{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/order_status.css' %}">

<div class="sign_in_wrapper">
    <div class="sign_in_form">
        <h2>Description</h2>
        <hr>
        <div>
            <h3 style="margin-bottom: 2%;">Order description</h3>
            {{ order.description|linebreaks }}
            <h3 style="margin-bottom: 2%;">Dead line</h3>
            {{ order.deadline|linebreaks }}
        </div>
        <div class="buttons" style="margin: 2% 0 0 0 !important; display: block !important;">
            <div style="float: left !important;">
                <a href="{% url 'orders' %}" class="btn" target="_blank" >Back</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/user_profile/order.html
{% extends "index.html" %}

{% load static %}

{% block title %}Order{% endblock %}

{% block header %}Create order{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/create_order.css' %}">
<div class="sign_in_wrapper">
    <div class="sign_in_form">
        <h2>Create Order</h2>
        <form  action="{% url 'create_order' %}" method="POST">
                {{ form.non_field_errors }}
            {% csrf_token %}
            <div class="description_field">
                <label> Description </label> <br>
                {{form.description}}
                {{ form.description.errors }}
            </div>
            <div class="dead_line">
                <label> Deadline </label> <br>
                {{form.deadline}}
                {{ form.deadline.errors }}
            </div>
            <div >
                <input type="submit" value="Submit" class="buton buton-bg">
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user_profile/orders.html
{% extends "index.html" %}

{% load static %}

{% block title %}Orders{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/order_status.css' %}">
<script src="https://kit.fontawesome.com/f9c292dca4.js" crossorigin="anonymous"></script>
{% if orders %}
<div class="sign_in_wrapper">
    <div class="sign_in_form">
        <h2>Orders</h2>
        <hr>
        <div class="buttons">
            <div>
                <a href="{% url 'create_order' %}" class="btn ">Add order</a>
            </div>
            <div style="margin-left: 2%;">
                <a href="{% url 'chat:index' %}" class="btn" target="_blank">Chat</a>
            </div>
        </div>
        <table>
        <tr>
            <th>Date</th>
            <th>Status</th>
            <th>Price($)</th>
            <th>Deadline</th>
            <th>Paid</th>
            <th>Actions</th>
        </tr>
        {% for order in orders %}
        <tr>
            <td>{{order.created}}</td>
            <td id='status'>{{order.status}}</td>
            {% if order.price %}
                <td>{{order.price}}</td>
            {% else %}
                <td>
                   -
                </td>
            {% endif %}
            <td>{{order.deadline}}</td>
            <td>
                {% if order.paid %}
                    <i class="fas fa-times-circle"></i>
                {% else %}
                    <i class="fas fa-times-circle"></i>
                {% endif %}
            </td>
            <td>
                {% if order.file %}
                <form enctype="multipart/form-data" action="{% url 'download' path=order.file %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Download" class="btn btn-link btn-revoke submit-color">
                </form>
                {% endif %}
                <a href="{{order.get_absolute_url}}" class="btn btn-link btn-detail submit-color">Detail</a>
                {% if order.status == 'processing' %}
                    <form action="{{order.get_absolute_url}}" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="Revoke" class="btn btn-link btn-revoke submit-color">
                    </form>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </table>
        {% include  'pagination.html' with page=orders %}
    </div>
</div>
{% else %}
<div class="sign_in_wrapper">
    <div class="sign_in_form">
        <div class="no_order_message">
            <p>It seems like you didn't invested some money to us :( Maybe it's time to start? 😉</p>
        </div>
        <div class="buttons">
            <div>
                <a href="{% url 'create_order' %}" class="btn ">Add order</a>
            </div>
            <div style="margin-left: 2%;">
                <a href="{% url 'chat:index' %}" class="btn" target="_blank">Chat</a>
            </div>
        </div>
    </div>
</div>

{% endif %}
{% endblock %}