chat/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name="chat"

urlpatterns=[
    path('chat/',views.index,name='index'),
    path('chat/<int:id>/',views.get_messages,name='messages'),
]

web_studio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('',include('homepage.urls')),
    path('',include('user_profile.urls')),
    path('',include('chat.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('jet/',include('jet.urls','jet')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.STATIC_ROOT)

chat/models.py
from django.db import models
from django.contrib.auth.models import User

class Message(models.Model):
    user=models.ForeignKey(User,related_name='messages', on_delete=models.CASCADE)
    message=models.TextField(max_length=3000)
    created=models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table='messages'

    def __str__(self):
        return self.message

class Chat(models.Model):
    users=models.ManyToManyField(User,related_name='chat_users',blank=True)
    messages=models.ManyToManyField(Message,blank=True)

    class Meta:
        db_table='chats'

    def __str__(self):
        return "{}".format(self.pk)

chat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from manager.models import Manager
from itertools import chain
from user_profile.models import Order
from django.http import JsonResponse, Http404
from .models import Message, Chat
from django.shortcuts import get_object_or_404

app_name = 'chat'

@login_required
def index(request):
    user = request.user
    chats = Chat.objects.filter(users=user)
    f_user=chats[0].users.exclude(id=user.id)[0]
    # f_user=User.objects.exclude(id=user.id)[0]
    messages=chats[0].messages.all()
    return render(request,'chat/index.html',{'chats':chats,'f_user':f_user,'messages':messages})

@login_required
def get_messages(request, id):
    chat=get_object_or_404(Chat,pk=id)
    sender = request.user
    if request.method=='GET' and request.is_ajax():
        receiver=chat.users.exclude(id=sender.id)[0]
        messages=chat.messages.values()
        return JsonResponse({
        'chat_id': chat.id,
        'sender_id': sender.id,
        'receiver_f': receiver.first_name,
        'receiver_l': receiver.last_name,
        'receiver_email':receiver.email,
        'results': list(messages)})
    elif request.method=='POST' and request.is_ajax():
        data=request.POST.get('message')
        message=Message(message=data,user=sender)
        message.save()
        chat.messages.add(message)
        return JsonResponse({'message':message.message,'created':message.created})
    return Http404()

templates/chat/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Chat</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="#">
	<link href="{% static 'css/chat.css' %}" type="text/css" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
</head>

<body style="overflow: hidden;">
	<div class="layout">
		<div class="sidebar">
			<div class="container">
				<div class="tab-content">
					<div class="tab-pane fade show active" id="conversations" role="tabpanel">
						<div class="middle">
							<h4>Chats</h4>
							<hr>
							<ul class="nav discussions" role="tablist">
								{% for chat in chats %}
								{% for u in chat.users.all %}
								{% if u.id != user.id %}
								<li>
									<a href="{% url 'chat:messages' chat.id %}" class="contact filter direct active"
										data-chat="open" data-toggle="tab" role="tab" aria-controls="chat1" chat-id={{chat.id}}
										aria-selected="true">
										<div class="status online"><img src="{% static 'img/avatars/user.svg' %}"
												alt="avatar"></div>
										<div class="content">
											<div class="headline">
												<h5>{{u.first_name}} {{u.last_name}}</h5>
												{% if u.is_superuser %}
												<span>Admin</span>
												{% elif u.is_staff %}
												<span>Manager</span>
												{% endif %}
											</div>
										</div>
									</a>
								</li>
								{% endif %}
								{% endfor %}
								{% endfor %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Start of Chat -->
		<div class="chat" id="chat-close">
			<div class="tab-content">
				<div class="tab-pane fade show active" id="chat1" role="tabpanel">
					<div class="item">
						<div class="content" style="padding: 0 20px;">
							<div class="container">
								<div class="top">
									<div class="headline">
										<img src="{% static 'img/avatars/user.svg' %}" alt="avatar">
										<div id="info-user" class="content" style="margin-top: -25px;">
											<h5>{{admin.first_name}}</h5>
											<span>{{admin.last_name}}</span>
										</div>
									</div>
										<button type="submit" class="btn prepend open-side-bar" style="margin-right:2%;position:relative;">
											<i data-eva="arrowhead-left"></i>
										</button>
								</div>
							</div>
							<div class="middle" id="scroll">
								<div class="container" style="width: 100%;">
									<ul id="chat">
										{% for message in messages %}
										{% if message.user.id == user.id %}
										<li>
											<div class="content">
												<div class="message">
													<div class="bubble">
														<p>{{message.message}}</p>
													</div>
												</div>
												<span>{{ message.created }}</span>
											</div>
										</li>
										{% else %}
										<li>
											<img src="../../static/img/avatars/user.svg" alt="avatar">
											<div class="contentRevers">
												<div class="message">
													<div class="bubble">
														<p>{{message.message}}</p>
													</div>
												</div>
												<span>{{ message.created }}</span>
											</div>
										</li>
										{% endif %}
										{% endfor %}
									</ul>
								</div>
							</div>
							<div class="container">
								<div class="bottom">
									<form id="sender-form" action="#" method="POST">
										{% csrf_token %}
										<input id="message" class="form-control" placeholder="Type message..." style="width: 90%;">
										<button type="submit" class="btn prepend"><i
												data-eva="paper-plane"></i></button>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"
		integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
	<script src="{% static 'js/vendor/popper.min.js' %}"></script>
	<script src="{% static 'js/vendor/feather.min.js' %}"></script>
	<script src="{% static 'js/vendor/eva.min.js' %}"></script>
	<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/swipe.min.js' %}"></script>
	<script src="{% static 'js/chat.js' %}"></script>
</body>

</html>